<?php

/**
 * @file
 * Provides a contributors entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function api_contributors_om_theme() {
  return [
    'contributors' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for contributors templates.
 *
 * Default template: contributors.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the contributors information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_contributors(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

// Example to fetch comments of a user.
// function api_contributors_om_preprocess(){
//   $filters = [
//     'name' => 'omkar-pd',
//     'limit' => 50,
//     'sort' => 'created',
//     'direction' => 'desc',
// ];
//   $response = \Drupal::service('api_contributors_om.profile')->sendRequest('comment', $filters);
// }
